-- Parkour tuning values. Keep traversal thresholds centralized so behavior can
-- be adjusted without editing detection, movement, and mantle algorithms.
return {
	ClimbableTag = "Climbable",
	WallReach = 3.25,
	MaxGrabHeight = 4.5,
	HangDrop = 2.35,
	WallGap = 0.8,
	TraverseSpeed = 7,
	TraverseSprintMultiplier = 1.7,
	VaultEnabled = true,
	VaultDetectionDistance = 4,
	VaultDetectionHeight = 0.4,
	VaultMinHeight = 0.3,
	VaultMaxHeight = 4,
	VaultLandingGap = 0.75,
	VaultMaxHopDistance = 5.5,
	VaultTopLandingInset = 1,
	VaultLandingHeightTolerance = 1.1,
	VaultMinArcHeight = 0.8,
	VaultMaxArcHeight = 4,
	VaultObstacleClearance = 0.2,
	VaultDuration = 0.38,
	VaultCooldown = 0.55,
	VaultForwardDot = 0.6,
	ClimbSmoothness = 18,
	SurfaceProbe = 1.4,
	MaxTopSurfaceHits = 16,
	MantleMaxRise = 12.5,
	GroundMantleMaxRise = 3.5,
	MantleMaxInward = 8,
	MantleMaxOutward = 2,
	MantleMaxLateral = 5,
	MantleMinRise = 0.25,
	TraverseHeightTolerance = 1.5,
	CornerLockDistance = 1.75,
}
