--!strict
-- Checks weapon move timing against baked animation data (AnimationManifest,
-- generated by tests/tools/BakeAnimationManifest). The Catalog runs this on the
-- authored definition, so MoveDefaults are merged here the same way the
-- Validator merges them. Malformed values are skipped: the Validator reports
-- them. Moves whose animation id has no manifest entry are not checked.
local AnimationContracts = {}

-- Marker times are baked from keyframes; allow for float rounding.
local MARKER_EPSILON = 1e-3

export type ManifestEntry = { Length: number, Markers: { HitStart: number?, HitStop: number? } }
export type Manifest = { [string]: ManifestEntry }

local function finite(value: any): boolean
	return type(value) == "number" and value == value and value ~= math.huge and value ~= -math.huge
end

-- A move field with MoveDefaults applied (authored keys win).
local function field(move: { [string]: any }, defaults: { [string]: any }?, key: string): any
	local value = move[key]
	if value == nil and defaults then
		return defaults[key]
	end
	return value
end

local function check_move(
	errors: { string },
	path: string,
	move: { [string]: any },
	defaults: { [string]: any }?,
	manifest: Manifest
)
	local animation = field(move, defaults, "Animation")
	if type(animation) ~= "table" or type(animation.Id) ~= "string" then
		return
	end
	-- Manifest content is generated data; shapes are checked before use.
	local entry: any = manifest[animation.Id]
	if type(entry) ~= "table" then
		return
	end
	local markers: any = if type(entry.Markers) == "table" then entry.Markers else {}
	local kind = field(move, defaults, "Kind")
	local hit_start_at = field(move, defaults, "HitStartAt")
	local hit_window = field(move, defaults, "HitWindow")
	local min_duration = field(move, defaults, "MinDuration")
	local hit_start = markers.HitStart
	local hit_stop = markers.HitStop

	if kind == "Charge" and not finite(hit_start) then
		table.insert(
			errors,
			("%s.Animation: %s has no HitStart marker, which a Charge move pauses on"):format(path, animation.Id)
		)
	end
	if finite(hit_start_at) and finite(hit_start) and hit_start_at > hit_start + MARKER_EPSILON then
		table.insert(
			errors,
			("%s.HitStartAt: must be <= the HitStart marker at %.3f in %s"):format(path, hit_start, animation.Id)
		)
	end
	if
		kind == "Light"
		and finite(hit_start_at)
		and finite(hit_window)
		and finite(hit_stop)
		and hit_start_at + hit_window < hit_stop
	then
		table.insert(
			errors,
			("%s.HitWindow: HitStartAt + HitWindow must reach the HitStop marker at %.3f in %s"):format(
				path,
				hit_stop,
				animation.Id
			)
		)
	end
	if finite(min_duration) and finite(entry.Length) and min_duration > entry.Length then
		table.insert(
			errors,
			("%s.MinDuration: must be <= the animation length %.3f of %s"):format(path, entry.Length, animation.Id)
		)
	end
end

-- Returns every contract violation of `definition` (weapon `id`) against
-- `manifest`. Error paths look like "Katana.Moves.Heavy.HitStartAt".
function AnimationContracts.check(definition: any, id: string, manifest: any): { string }
	local errors = {}
	if type(definition) ~= "table" or type(manifest) ~= "table" or type(definition.Moves) ~= "table" then
		return errors
	end
	local defaults = if type(definition.MoveDefaults) == "table" then definition.MoveDefaults else nil

	-- Sorted so the error order is stable.
	local names = {}
	for name, move in pairs(definition.Moves) do
		if type(name) == "string" and type(move) == "table" then
			table.insert(names, name)
		end
	end
	table.sort(names)
	for _, name in ipairs(names) do
		check_move(errors, ("%s.Moves.%s"):format(id, name), definition.Moves[name], defaults, manifest)
	end
	return errors
end

return table.freeze(AnimationContracts)
